### ISSUE TITLE
Question when using eslintrc in json format

### ISSUE THREAD

**Issue by HugoGresse** [godaddy/eslint-plugin-i18n-json#31]
Hi,

My project is using[ .eslintrc](https://github.com/HugoGresse/open-feedback/blob/master/.eslintrc) in `json` format which is supported by [Hound](https://houndci.com/) check on GitHub. 
However, Hound does not support `js` eslint config. 
I understand that Hound could probably support that, but on eslint side, is there a way to use the `identical-keys` while using `.json` format where import/require are not supported? 

Full PR is there to add eslint-plugin-i18n-json support: https://github.com/HugoGresse/open-feedback/pull/546/files

**Comment by mayank23** [comment]
Hi!

Maybe you can try placing absolute paths like so:

```json
{
  "rules": {
    "i18n-json/identical-keys": [2, {
      "filePath": "path/to/locale/en-US.json"
    }],
  },
}
```

**Comment by HugoGresse** [comment]
using absolute path it depends on each developer system directory :/

**Comment by mayank23** [comment]
Ah yes, true. Try the following as a short term fix 😉 : 

we require the files from `node_modules/eslint-plugin-i18n-json/src/util/require-no-cache.js`. So for example, if I am in my project folder, I can have the following directory structure

```
my-project/
    translations/ 
        en-US.json
    node_modules/
        eslint-plugin-i18n-json/
            src/
                util/
                    require-no-cache.js
```


For the require we need to go back 4 folders (from node_modules/eslint-plugin-i18n-json/src/util/require-no-cache.js) in order to get to our translation file 

Since `require` will first try to resolve from the predefined `__dirname`. And the `__dirname` for `require-no-cache.js` is going to be ` node_modules/eslint-plugin-i18n-json/src/util. 

So you can set this as the relative path to your file (go back 4 folders to get my project directory): `../../../../translations/en-US.json`. It should work then.

In your configuration 

```
{
  "rules": {
    "i18n-json/identical-keys": [2, {
      "filePath": "../../../../translations/en-US.json"
    }],
  },
}
```

**Comment by HugoGresse** [comment]
It's working 🎉
![bananadance](https://user-images.githubusercontent.com/662377/77744629-29be0100-701a-11ea-9f45-03dcd84cb649.gif)

thanks for your help @mayank23 

[PR on my project](https://github.com/HugoGresse/open-feedback/pull/546/checks?check_run_id=538989513)
